name: "Build"
on:
  push:
  workflow_dispatch:
jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build
        run: |
          sudo apt-get install autoconf pkg-config libprotobuf-c-dev protobuf-compiler libssl-dev
          RUST_LOG=debug cargo build -p example -vvv

  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build
        run: |
          choco install openssl
          choco install protoc
          git clone --depth 1 --branch v3.20.1 https://github.com/protocolbuffers/protobuf
          $Env:CPLUS_INCLUDE_PATH = "C:\Program Files\OpenSSL-Win64\include\;$((Get-Location).Path)\protobuf\src"
          cargo build -p gns -vvv
